### ISSUE TITLE
Inequality operator is not recognized

### ISSUE THREAD

**Issue by meisterluk** [FoamScience/maximalexer#1]
Hi,

I have come across an issue with maximalexer. The [inequality operator](http://eagle.cs.kent.edu/MAXIMA/maxima_5.html#IDX54) is not recognized as such. For example, consider the following input:

```maxima
(%i10) M:matrix([1,2],[3,4]);
                                   [ 1  2 ]
(%o10)                             [      ]
                                   [ 3  4 ]
(%i11) determinant(M);
(%o11)                                - 2
(%i12) is(determinant(M)#0);
(%o12)                               true
```
The final query asks “is the determinant of M not equal to 0”. I am using maximalexer with CTAN's minted. Minted generates the following output (to be used by LaTeχ):
```
\PYG{k+kt}{is}\PYG{p}{(}\PYG{k+kt}{determinant}\PYG{p}{(}\PYG{n}{M}\PYG{p}{)}\PYG{err}{\PYGZsh{}}\PYG{l+m+mi}{0}\PYG{p}{);;}
```
Recognize that `\PYG{err}` indicates an error even though the syntax was correct.

**Comment by meisterluk** [comment]
Recognize that the inequality operator `#` is missing on [line 41](https://github.com/FoamScience/maximalexer/blob/65a4eabbf7d1513666a36aa828f80ca281cf882b/MaximaLexer/maximalexer/maximalexer.py#L41), but adding it does not seem to suffice for my testcase.

**Update:** Sorry, caching lead me to a wrong conclusion. It fixes the problem.

**Comment by FoamScience** [comment]
Thanks for your contribution, I'll also update the pypi package as requested.

**Comment by FoamScience** [comment]
Thanks for your contribution, I'll also update the pypi package as requested.
